### PR TITLE
EN6-9 Removing client stuff from EntandoAuth, now Entando User Management

### PR DESCRIPTION
**Pull request by sergiofilhowz**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ampie** [comment]
[83% (+83.36%) vs master 0%](https://jenkins.entandocloud.com/job/de-entando-user-mgmt-pr/6/)

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Pull request merged**
